<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="T3J45" ignored="0" name="Default test" tests="5" failures="4" timestamp="2020-06-01T16:24:08 IST" time="149.924" errors="0">
  <testcase name="runScenario" time="32.182" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="22.043" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testrunner.Steps.page_titles_should_be(Steps.java:59)
at ✽.Page titles should be "Stack Overflow - Where Developers Learn, Share, & Build Careers"(classpath:testrunner/LoginWithData.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="22.989" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testrunner.Steps.page_titles_should_be(Steps.java:63)
at ✽.Page titles should be "Stack Overflow - Where Developers Learn, Share, & Build Careers"(classpath:testrunner/LoginWithData.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="31.113" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [Stack Overflow - Where Developers Learn, Share, &amp;amp; Build Careers] but found [Log In - Stack Overflow]">
      <![CDATA[java.lang.AssertionError: expected [Stack Overflow - Where Developers Learn, Share, & Build Careers] but found [Log In - Stack Overflow]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testrunner.Steps.page_titles_should_be(Steps.java:68)
at ✽.Page titles should be "Stack Overflow - Where Developers Learn, Share, & Build Careers"(classpath:testrunner/LoginWithData.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="40.578" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testrunner.Steps.page_titles_should_be(Steps.java:63)
at ✽.Page titles should be "Stack Overflow - Where Developers Learn, Share, & Build Careers"(classpath:testrunner/LoginWithData.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
